baseURL = "www.example.com"
languageCode = "en-us"
title = "WhaleDAO"

[params]
google_analytics_id = ""
google_tag_manager_id = ""

  [params.homepage]
  show_call_box = true
  hide_view_all_services = false

  [params.logo]
  mobile = "images/logo/logo-mobile.svg"
  desktop = "images/Logo.svg"
  desktop_height = "36px"
  alt = ""

  [params.homepage_meta_tags]
  meta_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
  meta_og_title = "Hugo Serif Theme"
  meta_og_type = "website"
  meta_og_url = "https://hugo-serif.netlify.app"
  meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
  meta_og_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
  meta_twitter_card = "summary"
  meta_twitter_site = "@zerostaticio"
  meta_twitter_creator = "@zerostaticio"

  [params.team]
  summary_large_truncate = 120

  [params.footer]
  copyright_text = 'Free Hugo theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>'

[[menu.main]]
name = "Services"
url = "/services/"
weight = 1

[[menu.main]]
name = "Team"
url = "/team/"
weight = 2

[[menu.footer]]
name = "Home"
url = "/"
weight = 1

[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 2
