baseURL = "www.example.com"
languageCode = "en-us"
title = "WhaleDAO"

[params]
google_analytics_id = ""
google_tag_manager_id = ""

  [params.homepage]
  show_call_box = true
  hide_view_all_services = false

  [params.logo]
  mobile = "images/logo-web.svg"
  desktop = "images/modern-petunia.svg"
  desktop_height = "36px"
  alt = "WhaleDAO - Powered by DAOSquare"

  [params.homepage_meta_tags]
  meta_description = "WhaleDAO is incubated by DAOSquare and is committed to helping high-quality projects around the world build their ecosystem in the Greater China region."
  meta_og_title = "WhaleDAO"
  meta_og_type = "website"
  meta_og_url = "https://whaledao.org"
  meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
  meta_og_description = "WhaleDAO is incubated by DAOSquare and is committed to helping high-quality projects around the world build their ecosystem in the Greater China region."
  meta_twitter_card = "summary"
  meta_twitter_site = "@DAOSquare"
  meta_twitter_creator = "@DAOSquare"

  [params.team]
  summary_large_truncate = 120

  [params.footer]
  copyright_text = 'Powered by <a class="DAOSquare" href="https://www.daosquare.io">DAOsquare</a>'

[[menu.main]]
name = "Services"
url = "/services/"
weight = 1

[[menu.main]]
name = "Team"
url = "/team/"
weight = 2

[[menu.footer]]
name = "Home"
url = "/"
weight = 1

[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 2
