name = "Hugo Serif"
license = "MIT"
licenselink = "https://github.com/zerostaticthemes/hugo-serif-theme/blob/master/LICENSE"
description = "Serif is an advanced multi page theme for Hugo. It contains multiple content types for a typical business website. The theme is fully responsive, blazing fast and artfully illustrated."
homepage = "https://github.com/zerostaticthemes/hugo-serif-theme"
tags = ["responsive","minimal","clean","business","multi page", "marketing", "company","bootstrap","zerostatic","personal","google analytics"]
features = ["services","team","about","contact"]
min_version = "0.74.3"

[author]
  name = "Robert Austin"
  homepage = "https://www.zerostatic.io"
